### PR TITLE
feat(FE-90): Signup & Login navigation

### PR DESCRIPTION
**Pull request by Opeyimika-sudo**
This pull request does the following for both the signup and login pages: 
i) Worked on the logo not remaining in the background on scroll,
ii) Made the mobile version responsive with media queries on font size and spacing (margin and padding)

Linear ID: https://linear.app/team-repute/issue/FRO-90/signup-and-login-navigation

### CODE REVIEW

**Comment by Johnoris** [comment]
fix the logo that is fixed on mobile screens

**Comment by Johnoris** [comment]
The forgot password links no where

**Comment by Opeyimika-sudo** [comment]
The forgot password link is on the other branch (FE-89).
Bruh, it works.
I've tested it over and over again

**Comment by Opeyimika-sudo** [comment]
I've removed "iii) Made a link for the Forgot password on the Login page" from the PR.  Will include it in 89

**Comment by Johnoris** [comment]
okay nice

**Pull request merged**
