### PR TITLE
feat(FE-89): made the Forgot password page

### PR DESCRIPTION
**Pull request by Opeyimika-sudo**
This pull request does the following:
i) Made a link for the Forgot password on the Login page 
ii) On clicking "Forgot password" on the Login screen, you are taken to a "Forgot password" page where you are asked for your email address
iii) On filling in a valid email address, you are taken to a "Change password" page where you set and confirm your new password
iv) If the new password is confirmed, a password reset successful modal pops up which when clicked takes you to your dashboard
v)If the new password is not confirmed, a password reset failed modal pops up which when clicked takes you to the start of the process - the "Forgot password" page

Linear ID: https://linear.app/team-repute/issue/FRO-89/forgot-password-creation

### CODE REVIEW

**Comment by Johnoris** [comment]
describe what this PR should do properly

**Comment by Johnoris** [comment]
Broooo...why you go use alert....message a designer they know what should be there

**Comment by Opeyimika-sudo** [comment]
Bruh, @Johnoris I've updated this one with the routing for Login as it should be.

**Comment by Johnoris** [comment]
boss please fix the merge conflicts

**Pull request merged**
